server:
  port: 8084

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example503_user
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    generate-ddl: true

application:
  name: user-service

jwt:
  secret: "[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$"

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
