server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example503_product
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    generate-ddl: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  # data:
  #   elasticsearch:
  #     client:
  #       reactive:
  #         endpoints: http://localhost:9200
  #     repositories:
  #       enabled: true

zipkin:
  base-url: http://localhost:9411

rabbitmq:
  addresses: localhost:5672

application:
  name: product-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
